[0m08:19:04.298820 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f904e440880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f904d5f16c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f904d5f1630>]}


============================== 08:19:04.304013 | c5dca4c5-0a87-4a04-b890-ee2a116d7ccf ==============================
[0m08:19:04.304013 [info ] [MainThread]: Running with dbt=1.9.3
[0m08:19:04.305085 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/kudadiri/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init KudadiriShop', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m08:19:04.315219 [debug] [MainThread]: Starter project path: /home/kudadiri/anaconda3/envs/Home/lib/python3.10/site-packages/dbt/include/starter_project
[0m08:19:04.320505 [info ] [MainThread]: 
Your new dbt project "KudadiriShop" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m08:19:04.321319 [info ] [MainThread]: Setting up your profile.
[0m08:19:27.802007 [error] [MainThread]: Encountered an error:

[0m08:19:27.806997 [error] [MainThread]: Traceback (most recent call last):
  File "/home/kudadiri/anaconda3/envs/Home/lib/python3.10/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/kudadiri/anaconda3/envs/Home/lib/python3.10/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/kudadiri/anaconda3/envs/Home/lib/python3.10/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
  File "/home/kudadiri/anaconda3/envs/Home/lib/python3.10/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/home/kudadiri/anaconda3/envs/Home/lib/python3.10/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/home/kudadiri/anaconda3/envs/Home/lib/python3.10/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/home/kudadiri/anaconda3/envs/Home/lib/python3.10/site-packages/dbt/task/init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "/home/kudadiri/anaconda3/envs/Home/lib/python3.10/site-packages/dbt/task/init.py", line 113, in generate_target_from_input
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/home/kudadiri/anaconda3/envs/Home/lib/python3.10/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/home/kudadiri/anaconda3/envs/Home/lib/python3.10/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m08:19:27.809924 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 23.597725, "process_in_blocks": "203584", "process_kernel_time": 0.812145, "process_mem_max_rss": "227656", "process_out_blocks": "80", "process_user_time": 3.632704}
[0m08:19:27.811275 [debug] [MainThread]: Command `dbt init` failed at 08:19:27.810976 after 23.60 seconds
[0m08:19:27.812416 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f904e440880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9030fd1630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9030fd27a0>]}
[0m08:19:27.813675 [debug] [MainThread]: Flushing usage events
[0m08:19:31.943294 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:20:18.337779 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4e407088b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4e3f8d96f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4e3f8d9690>]}


============================== 08:20:18.341799 | 841b9c31-32f2-4215-8a4a-766ae158f8a8 ==============================
[0m08:20:18.341799 [info ] [MainThread]: Running with dbt=1.9.3
[0m08:20:18.343231 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/kudadiri/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init KudadiriShop_SACredential', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m08:20:18.359967 [debug] [MainThread]: Starter project path: /home/kudadiri/anaconda3/envs/Home/lib/python3.10/site-packages/dbt/include/starter_project
[0m08:20:18.368721 [info ] [MainThread]: 
Your new dbt project "KudadiriShop_SACredential" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m08:20:18.370628 [info ] [MainThread]: Setting up your profile.
[0m08:26:17.065861 [info ] [MainThread]: Profile KudadiriShop_SACredential written to /home/kudadiri/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m08:26:17.068315 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 327.92252, "process_in_blocks": "0", "process_kernel_time": 0.51039, "process_mem_max_rss": "224864", "process_out_blocks": "80", "process_user_time": 3.865939}
[0m08:26:17.069206 [debug] [MainThread]: Command `dbt init` succeeded at 08:26:17.069035 after 327.92 seconds
[0m08:26:17.069807 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4e407088b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4e3f8d9f00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4e3f8d96f0>]}
[0m08:26:17.070754 [debug] [MainThread]: Flushing usage events
[0m08:26:18.442180 [debug] [MainThread]: An error was encountered while trying to flush usage events
